### ISSUE TITLE
[approve]: the suggestion comments make author easily misunderstood

### ISSUE THREAD

**Issue by wuhuizuo** [ti-community-infra/test-infra#42]
![img_v3_026h_008088bd-0e5c-4fc0-a4dc-e385106e83cg](https://github.com/ti-community-infra/test-infra/assets/2574558/6a22e1fa-a0e9-4c9e-9502-30b9c09852f3)
the suggestion comment should be "all" logic not "any" logic.

expect: "please assign both X and Y for approvals".

**Comment by purelind** [comment]
The sentence "please assign ywqzzy, tangenta, eason7 for approval" could potentially lead to ambiguity, as it might imply that approval from any one of the three individuals would be sufficient. To eliminate any confusion and clarify that approval is required from all three individuals, you could rephrase the instruction as follows:

"please assign ywqzzy, tangenta, eason7  for approval, ensuring that each of them provides their approval before proceeding"
